package com.ifes.bilheteria.gui.cadastro;

import com.ifes.bilheteria.acessoadados.*;
import com.ifes.bilheteria.entidades.*;
import com.ifes.bilheteria.entidades.conversores.ConversorDeDuracaoFormatada;
import com.ifes.bilheteria.enums.*;
import com.ifes.bilheteria.gui.interfaces.*;

import static com.ifes.bilheteria.gui.UtilsGUI.*;

public class CadastroDeTeatro extends javax.swing.JFrame implements ConfiguracaoDeJFrame, UtilizadorDeSelecionadorDeData, UtilizadorDeSelecionadorDeHorario {

    private SelecionadorDeData selecionadorDeData;
    private SelecionadorDeHorario selecionadorDeHorario;

    public CadastroDeTeatro() {
        initComponents();
        configurar();
        
        campoData.setEditable(false);
        campoData.setEnabled(false);
        campoHorario.setEditable(false);
        campoHorario.setEnabled(false);

        String[] classificacoes = ParseadorDeClassificacaoIndicativa.preencherArray();
        renderizarJComboBox(comboBoxClassificacaoIndicativa, classificacoes);

        String[] cidades = ParseadorDeCidade.preencherArray();
        renderizarJComboBox(comboBoxCidades, cidades);

        String[] generos = ParseadorDeGenero.preencherArray();
        renderizarJComboBox(comboBoxGenero, generos);

        String[] duracoes = ParseadorDeDuracao.preencherArray(600);
        renderizarJComboBox(comboBoxDuracao, duracoes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoData = new javax.swing.JTextField();
        botaoSelecionarData = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoHorario = new javax.swing.JTextField();
        botaoSelecionarHorario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboBoxClassificacaoIndicativa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboBoxGenero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        comboBoxDuracao = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboBoxCidades = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nome da peça");

        campoNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Data");

        campoData.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botaoSelecionarData.setText("SELECIONAR");
        botaoSelecionarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarDataActionPerformed(evt);
            }
        });

        jLabel4.setText("Horário");

        campoHorario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botaoSelecionarHorario.setText("SELECIONAR");
        botaoSelecionarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarHorarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Classificação indicativa");

        comboBoxClassificacaoIndicativa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Gênero");

        comboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Duração");

        comboBoxDuracao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("CADASTRAR TEATRO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Cidade");

        comboBoxCidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(campoNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSelecionarData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSelecionarHorario))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(comboBoxClassificacaoIndicativa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(comboBoxCidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSelecionarData))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSelecionarHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxCidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxClassificacaoIndicativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSelecionarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarDataActionPerformed
        if (selecionadorDeData == null) {
            selecionadorDeData = new SelecionadorDeData(this);
            selecionadorDeData.setVisible(true);
        }

        deixarJanelaVisivelCasoEstejaInvisivel(selecionadorDeData);
    }//GEN-LAST:event_botaoSelecionarDataActionPerformed

    private void botaoSelecionarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarHorarioActionPerformed
        if (selecionadorDeHorario == null) {
            selecionadorDeHorario = new SelecionadorDeHorario(this);
            selecionadorDeHorario.setVisible(true);
        }

        deixarJanelaVisivelCasoEstejaInvisivel(selecionadorDeHorario);
    }//GEN-LAST:event_botaoSelecionarHorarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (camposDeTextoEstaoValidos()) {
            String nome = campoNome.getText().trim();
            Data data = getDataSelecionada();
            Horario horario = getHorarioSelecionado();
            ClassificacaoIndicativa classificacao = definirClassificacaoIndicativa(comboBoxClassificacaoIndicativa);

            String nomeDaCidade = obterItemSelecionadoConvertidoEmString(comboBoxCidades);
            int idCidade = new ParseadorDeCidade().obterIdDaCidadeBaseadoNoNome(nomeDaCidade);
            Cidade cidade = new Cidade(idCidade, nomeDaCidade);

            ConversorDeDuracaoFormatada conversor = new ConversorDeDuracaoFormatada(obterItemSelecionadoConvertidoEmString(comboBoxDuracao));
            Duracao duracao = conversor.converterStringFormatada();

            Genero genero = Genero.valueOf(obterItemSelecionadoConvertidoEmString(comboBoxGenero).toUpperCase());

            Evento evento = new Teatro(nome, data, Categoria.TEATRO, horario, cidade, classificacao, duracao, genero);
            EscritorDeCSV escritor = new EscritorDeCSV(Destino.TEATRO);
            escritor.escreverEventoNoArquivoCSV(evento);

            exibirMensagemNaTela("TEATRO CADASTRADO!");
        } else {
            exibirMensagemNaTela("Preencha todos os campos!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean camposDeTextoEstaoValidos() {
        ValidadorDeCampos validador = new ValidadorDeCampos();
        return validador.camposPossuemAlgumTexto(campoData, campoHorario, campoNome);
    }

    private Data getDataSelecionada() {
        return new Data(campoData.getText());
    }

    private Horario getHorarioSelecionado() {
        return new Horario(campoHorario.getText());
    }

    @Override
    public void renderizar(Data data) {
        campoData.setText(data.getDataFormatada());
        campoData.setEnabled(true);
        botaoSelecionarData.setText("EDITAR");
    }

    @Override
    public void renderizar(Horario horario) {
        campoHorario.setText(horario.getHoraFormatada());
        campoHorario.setEnabled(true);
        botaoSelecionarHorario.setText("EDITAR");
    }

    @Override
    public void centralizarTela() {
        centralizarTelaNoMeio(this);
    }

    @Override
    public void acaoAoClicarEmFechar() {
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    @Override
    public void configurar() {
        centralizarTela();
        acaoAoClicarEmFechar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeTeatro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSelecionarData;
    private javax.swing.JButton botaoSelecionarHorario;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoHorario;
    private javax.swing.JTextField campoNome;
    private javax.swing.JComboBox<String> comboBoxCidades;
    private javax.swing.JComboBox<String> comboBoxClassificacaoIndicativa;
    private javax.swing.JComboBox<String> comboBoxDuracao;
    private javax.swing.JComboBox<String> comboBoxGenero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
